name: Simple CI/CD 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Install dependencies 
      run: make install 
    
    - name: Lint
      run: make lint
